version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hzrd149-nsecbunker_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/hzrd149/nsecbunker-admin-ui:0.1.0
    restart: on-failure
    stop_grace_period: 1m
    init: true

  migrations:
    image: ghcr.io/hzrd149/nsecbunkerd:0.10.2
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      DATABASE_URL: "file:/data/nsecbunker.db"
    restart: no
    entrypoint: ""
    command:
      - npx
      - prisma
      - migrate
      - deploy

  nsecbunkerd:
    image: ghcr.io/hzrd149/nsecbunkerd:0.10.2
    restart: unless-stopped
    pids_limit: 100
    mem_limit: 256mb
    memswap_limit: 256mb
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      DATABASE_URL: "file:/data/nsecbunker.db"
      # ADMIN_NPUBS: ...
    command:
      - start
      - -c=/data/nsecbunker.json
    ports:
      - "3000:3000"
    depends_on:
      - migrations
