#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"

[ ! -d "${APP_DATA_DIR}/Blossom" ] && mkdir -p "${APP_DATA_DIR}/Blossom"
[ ! -d "${APP_DATA_DIR}/config" ] && mkdir -p "${APP_DATA_DIR}/config"

# Always change the user for app data dir
chown 1000:1000 "${APP_DATA_DIR}/Blossom"
chown 1000:1000 "${APP_DATA_DIR}/config"
