version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hzrd149-nostr-secretary_server_1
      APP_PORT: 8080
  server:
    image: ghcr.io/hzrd149/nostr-secretary:0.3.1@sha256:8699e3cc99bf298c94c23628511c953bb84838777bad1a231ea56dc46c030f2c
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}:/app/data
