version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hzrd149-nostr-secretary_server_1
      APP_PORT: 8080
  server:
    image: ghcr.io/hzrd149/nostr-secretary:0.3.0@sha256:7ea0ba80acb0840b4cabf2f3fc4b5ca5acb3a99c2205dcc7e75f027da2c42baf
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}:/app/data
