version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: hzrd149-coracle_web_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/hzrd149/coracle:sha-1733c5f
    restart: on-failure
    stop_grace_period: 1m
    init: true
